from django.db import models

class Player(models.Model):
    cID = models.CharField(max_length = 20)
    password = models.CharField(max_length = 20)
    Room = models.IntegerField (default = 0)

class Room(models.Model):
    num = models.AutoField(primary_key =True)
    User0 = models.CharField(max_length = 20, default = "")
    User1 = models.CharField(max_length = 20, default = "")
    User2 = models.CharField(max_length = 20, default = "")
    User3 = models.CharField(max_length = 20, default = "")
    turn = models.IntegerField (default = 0)
    thrown = models.CharField(max_length = 1000, default = "")
    start = models.BooleanField(default = False)
    Deck = models.CharField(max_length = 1000, default = "")
    Flag0 = models.BooleanField(default = False)
    Flag1 = models.BooleanField(default = False)
    Flag2 = models.BooleanField(default = False)
    Flag3 = models.BooleanField(default = False)
    Tchu0 = models.IntegerField(default = 0)
    Tchu1 = models.IntegerField(default = 0)
    Tchu2 = models.IntegerField(default = 0)
    Tchu3 = models.IntegerField(default = 0)
    lFlag0 = models.BooleanField(default = False)
    lFlag1 = models.BooleanField(default = False)
    lFlag2 = models.BooleanField(default = False)
    lFlag3 = models.BooleanField(default = False)
    sFlag0 = models.BooleanField(default = False)
    sFlag1 = models.BooleanField(default = False)
    sFlag2 = models.BooleanField(default = False)
    sFlag3 = models.BooleanField(default = False)
    eFlag0 = models.BooleanField(default = False)
    eFlag1 = models.BooleanField(default = False)
    eFlag2 = models.BooleanField(default = False)
    eFlag3 = models.BooleanField(default = False)
    eCard0 = models.CharField(max_length = 100)
    eCard1 = models.CharField(max_length = 100)
    eCard2 = models.CharField(max_length = 100)
    eCard3 = models.CharField(max_length = 100)
    wFlag0 = models.BooleanField(default = False)
    wFlag1 = models.BooleanField(default = False)
    wFlag2 = models.BooleanField(default = False)
    wFlag3 = models.BooleanField(default = False)
    fFlag0 = models.BooleanField(default = False)
    fFlag1 = models.BooleanField(default = False)
    fFlag2 = models.BooleanField(default = False)
    fFlag3 = models.BooleanField(default = False)
